name: Work 1 Edgar
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container: node:16
    steps:
      - uses: actions/checkout@v3
      - run: node server.js
      - run: node --version
      - run: echo "SI727576"
